save_path: wn18rr/multitask_lexname_adaptive_mid
load_path: null
seed: 1

data:
  data_path: ../data/wn18rr
  rule_file: ../data/wn18rr/mined_rules.txt
  batch_size: 8

EM:
  num_iters: 2            # 原本是 5
  prior_weight: 0.001
  num_rules: 30           # 原本是 100
  max_length: 3

generator:
  gpu: 0
  model:
    embedding_dim: 512
    hidden_dim: 256
    num_layers: 1
  pre_train:
    num_epoch: 10000
    lr: 0.001
    print_every: 1000
    batch_size: 512
  train:
    num_epoch: 100
    lr: 0.00001
    print_every: 1000
    batch_size: 512
  post_train:
    num_epoch: 1000
    lr: 0.00001
    print_every: 1000
    batch_size: 512

predictor:
  gpus: [0, 1]
  model:
    entity_feature: bias
  optimizer:
    lr: 0.001
    weight_decay: 0
  train:
    smoothing: 0.2
    batch_per_epoch: 10000     # ✅ 原本是 1000000
    print_every: 100
  eval:
    expectation: true
  H_score:
    print_every: 1000

final_prediction:
  num_iters: 1                 # ✅ 原本是 5
  num_rules: [30, 30, 50, 30, 30]
  max_length: [1, 2, 3, 4, 5]

predictorplus:
  gpus: [0, 1]
  model:
    hidden_dim: 16
    aggregator: pna
  optimizer:
    lr: 0.005
    weight_decay: 0
  train:
    smoothing: 0.2
    batch_per_epoch: 10000     # ✅ 快速測試
    print_every: 100
  eval:
    expectation: true
