save_path: results/semmeddb/sm_test/20250704_040759
load_path: null
seed: 1

data:
  data_path: ../data/semmeddb
  rule_file: ../data/semmeddb/mined_rules.txt
  cluster_size: 3
  relation_cluster_file: ../data/semmeddb/relation_cluster/matrix_3.dict
  batch_size: 8

EM:
  num_iters: 2
  prior_weight: 0.001
  num_rules: 10
  max_length: 3

generator:
  gpu: 1
  model:
    embedding_dim: 512
    hidden_dim: 256
    num_layers: 1
  pre_train:
    num_epoch: 10
    lr: 0.001
    print_every: 1
    batch_size: 512
  train:
    num_epoch: 10
    lr: 0.00001
    print_every: 1
    batch_size: 512
  post_train:
    num_epoch: 10
    lr: 0.00001
    print_every: 1
    batch_size: 512

predictor:
  gpus: [0]
  model:
    entity_feature: bias
  optimizer:
    lr: 0.001
    weight_decay: 0
  train:
    smoothing: 0.2
    batch_per_epoch: 1000
    print_every: 100
  eval:
    expectation: true
  H_score:
    print_every: 1000

final_prediction:
  num_iters: 1
  num_rules: [100]
  max_length: [1, 3, 5]

predictorplus:
  gpus: [0]
  model:
    hidden_dim: 16
    aggregator: sum
  optimizer:
    lr: 0.005
    weight_decay: 0
  train:
    smoothing: 0.2
    batch_per_epoch: 1000
    print_every: 100
  eval:
    expectation: true
